"""
    This file was automatically generated.  Please do not modify by hand.

    The code provides a mapping from Houdini parameters to the parameters
    needed for rendering.
"""

def initializeFeatures(settings):
    Renderer = settings.addGlobal
    Camera = settings.addGlobal
    Image = settings.addGlobal
    Photon = settings.addGlobal
    Object = settings.addObject
    Light = settings.addLight
    Fog = settings.addFog
    Geometry = settings.addGeometry
    Deep = settings.addDeepResolver
    Measure = settings.addMeasure
    Bokeh = settings.addBokeh
    IPlane = settings.addImagePlane
    ImageOption = settings.addImageOption

    # -- Renderer --
    Renderer("renderer", "abortmissingtexture", "bool", "vm_abort_missing_texture")
    Renderer("renderer", "alfprogress", "bool", "vm_alfprogress")
    Renderer("renderer", "bake_alphadestplanes", "string", "vm_bake_alphadestplanes")
    Renderer("renderer", "bake_normalizep", "bool", "vm_bake_normalizep")
    Renderer("renderer", "bake_normalsfaceforward", "bool", "vm_bake_normalsfaceforward")
    Renderer("renderer", "bake_udimrange", "string", "vm_bake_udimrange")
    Renderer("renderer", "bake_usemikkt", "bool", "vm_bake_usemikkt")
    Renderer("renderer", "bboxenablelod", "bool", "vm_bboxenablelod")
    Renderer("renderer", "blurquality", "bool", "vm_blurquality")
    Renderer("renderer", "bvhoriented", "bool", "vm_bvhoriented")
    Renderer("renderer", "cacheratio", "float", "vm_cacheratio")
    Renderer("renderer", "cachesize", "int", "vm_cachesize")
    Renderer("renderer", "colorspace", "string", "vm_colorspace", skipdefault=False)
    Renderer("renderer", "constrainmaxrough", "bool", "vm_constrainmaxrough")
    Renderer("renderer", "curvebunchsize", "int", "vm_curvebunchsize")
    Renderer("renderer", "dicingquality", "bool", "vm_dicingquality")
    Renderer("renderer", "diffusecomponents", "string", "vm_diffusecomponents")
    Renderer("renderer", "dofquality", "bool", "vm_dofquality")
    Renderer("renderer", "exportcomponents", "string", "vm_exportcomponents")
    Renderer("renderer", "extractimageplanes", "bool", "vm_extractimageplanes")
    Renderer("renderer", "extractimageplanesformat", "string", "vm_extractimageplanesformat")
    Renderer("renderer", "extractlinearplanes", "string", "vm_extractlinearplanes")
    Renderer("renderer", "extractremoveintermediate", "bool", "vm_extractremoveintermediate")
    Renderer("renderer", "extractseparator", "string", "vm_extractseparator")
    Renderer("renderer", "fogbackground", "bool", "vm_fogbackground")
    Renderer("renderer", "fogbackgroundshader", "string", "vm_fogbackgroundshader")
    Renderer("renderer", "fogimports", "string", "vm_fogimports")
    Renderer("renderer", "giquality", "bool", "vm_giquality")
    Renderer("renderer", "hidden", "bool", "vm_hidden")
    Renderer("renderer", "imageblur", "bool", "vm_imageblur")
    Renderer("renderer", "iprfakerelight", "bool", "vm_iprfakerelight")
    Renderer("renderer", "iprfixsamples", "bool", "vm_iprfixsamples")
    Renderer("renderer", "iprpasssamples", "float", "vm_iprpasssamples")
    Renderer("renderer", "kdmemfactor", "float", "vm_kdmemfactor")
    Renderer("renderer", "logcolors", "int", "vm_logcolors", skipdefault=False)
    Renderer("renderer", "logtimestamps", "bool", "vm_logtimestamps")
    Renderer("renderer", "measuremedian", "bool", "vm_measuremedian")
    Renderer("renderer", "nesteddielectric", "bool", "vm_nesteddielectric")
    Renderer("renderer", "networkcompress", "bool", "vm_networkcompress")
    Renderer("renderer", "networkqsize", "int", "vm_networkqsize")
    Renderer("renderer", "objroot", "string", "vm_objroot")
    Renderer("renderer", "octreestyle", "string", "vm_octreestyle")
    Renderer("renderer", "pathcutoff", "bool", "vm_pathcutoff")
    Renderer("renderer", "pathcutoffdepth", "int", "vm_pathcutoffdepth")
    Renderer("renderer", "pathcutoffmethod", "int", "vm_pathcutoffmethod")
    Renderer("renderer", "pathcutoffthresh", "float", "vm_pathcutoffthresh")
    Renderer("renderer", "pbrpathtype", "string", "vm_pbrpathtype")
    Renderer("renderer", "pbrssssamplingmode", "int", "vm_pbrssssamplingmode")
    Renderer("renderer", "preview", "bool", "vm_preview")
    Renderer("renderer", "previewadaptive", "bool", "vm_previewadaptive")
    Renderer("renderer", "previewadaptivefactor", "float", "vm_previewadaptivefactor")
    Renderer("renderer", "previewmode", "string", "vm_previewmode")
    Renderer("renderer", "previewmouseradius", "float", "vm_previewmouseradius")
    Renderer("renderer", "previewtime", "float", "vm_previewtime")
    Renderer("renderer", "ptexmapmaxres", "int", "vm_ptexmapmaxres")
    Renderer("renderer", "ptexmapminres", "int", "vm_ptexmapminres")
    Renderer("renderer", "ptexmapscale", "float", "vm_ptexmapscale")
    Renderer("renderer", "ptexrelativescale", "bool", "vm_ptexrelativescale")
    Renderer("renderer", "ptexscaleattr", "string", "vm_ptexscaleattr")
    Renderer("renderer", "ptexwraporient", "bool", "vm_ptexwraporient")
    Renderer("renderer", "raybias", "float", "vm_raybias")
    Renderer("renderer", "rayblurquality", "bool", "vm_rayblurquality")
    Renderer("renderer", "rayderivbias", "float", "vm_rayderivbias")
    Renderer("renderer", "rayderivrandom", "bool", "vm_rayderivrandom")
    Renderer("renderer", "raylimitcomponents", "string", "vm_raylimitcomponents")
    Renderer("renderer", "raylimiteval", "string", "vm_raylimiteval")
    Renderer("renderer", "raylimitlightmask", "string", "vm_raylimitlightmask")
    Renderer("renderer", "rayquality", "bool", "vm_rayquality")
    Renderer("renderer", "refractcomponents", "string", "vm_refractcomponents")
    Renderer("renderer", "relightingbuffer", "bool", "vm_relightingbuffer")
    Renderer("renderer", "renderengine", "string", "vm_renderengine", skipdefault=False)
    Renderer("renderer", "renderinterrupt", "bool", "vm_renderinterrupt")
    Renderer("renderer", "samplecachesize", "int", "vm_samplecachesize")
    Renderer("renderer", "shadingfactor", "float", "vm_shadingfactor")
    Renderer("renderer", "shadingqueuesize", "int", "vm_shadingqueuesize")
    Renderer("renderer", "ssscomponents", "string", "vm_ssscomponents")
    Renderer("renderer", "stylesheets", "bool", "vm_stylesheets")
    Renderer("renderer", "threadcount", "int", "vm_threadcount")
    Renderer("renderer", "tilecallback", "string", "vm_tilecallback")
    Renderer("renderer", "timelimit", "float", "vm_timelimit")
    Renderer("renderer", "unshadedlimit", "int", "vm_unshadedlimit")
    Renderer("renderer", "usecacheratio", "bool", "vm_usecacheratio")
    Renderer("renderer", "usemaxthreads", "int", "vm_usemaxthreads")
    Renderer("renderer", "uvattribute", "string", "vm_uvattribute")
    Renderer("renderer", "uvborderpixels", "int", "vm_uvborderpixels")
    Renderer("renderer", "uvmkpath", "bool", "vm_uvmkpath")
    Renderer("renderer", "uvpostprocess", "string", "vm_uvpostprocess")
    Renderer("renderer", "uvshadingquality", "float", "vm_uvshadingquality")
    Renderer("renderer", "uvtype", "string", "vm_uvtype")
    Renderer("renderer", "verbose", "int", "vm_verbose", skipdefault=False)
    Renderer("renderer", "vexprofile", "int", "vm_vexprofile")
    Renderer("renderer", "volumecomponents", "string", "vm_volumecomponents")

    # -- Image --
    Image("image", "background", "string", "vm_background")
    Image("image", "backgroundchannels", "string", "vm_backgroundchannels")
    Image("image", "backgroundmatte", "bool", "vm_backgroundmatte")
    Image("image", "batchmode", "bool", "vm_imagebatchmode")
    Image("image", "bgenable", "bool", "vm_bgenable")
    Image("image", "bgscale", "bool", "vm_bgscale")
    Image("image", "bgzscale", "float", "vm_bgzscale")
    Image("image", "bucket", "int", "vm_bucketsize")
    Image("image", "bucketthreadcolor", "bool", "vm_bucketthreadcolor")
    Image("image", "checkpointcachesize", "int", "vm_checkpointcachesize")
    Image("image", "checkpointname", "string", "vm_checkpointname")
    Image("image", "checkpointperiod", "float", "vm_checkpointperiod")
    Image("image", "colorlimit", "float", "vm_colorlimit")
    Image("image", "colorlimitdecay", "float", "vm_colorlimitdecay")
    Image("image", "colorlimitdepth", "int", "vm_colorlimitdepth")
    Image("image", "decorrelatedof", "bool", "vm_decorrelatedof")
    Image("image", "exrdatawindowpadding", "int", "vm_exrdatawindowpadding")
    Image("image", "exrdatawindowplanes", "string", "vm_exrdatawindowplanes")
    Image("image", "exrdatawindowthreshold", "float", "vm_exrdatawindowthreshold")
    Image("image", "iprbucket", "int", "vm_iprbucketsize")
    Image("image", "jitter", "float", "vm_jitter")
    Image("image", "matchdeeppixelfilter", "bool", "vm_matchdeeppixelfilter")
    Image("image", "opacitylimit", "float", "vm_opacitylimit")
    Image("image", "opacitythresh", "float", "vm_opacitythresh")
    Image("image", "overridecheckpointname", "bool", "vm_overridecheckpointname")
    Image("image", "randomseed", "int", "vm_randomseed")
    Image("image", "readcheckpoint", "bool", "vm_readcheckpoint")
    Image("image", "resolution", "int", "vm_uvunwrapres")
    Image("image", "samplelock", "bool", "vm_samplelock")
    Image("image", "samples", "int", "vm_samples", skipdefault=False)
    Image("image", "saveoptions", "string", "vm_saveoptions")
    Image("image", "setexrdatawindow", "bool", "vm_setexrdatawindow")
    Image("image", "subpixel", "bool", "vm_subpixel")
    Image("image", "transparent", "bool", "vm_transparent")
    Image("image", "transparentsamples", "int", "vm_transparentsamples")
    Image("image", "writecheckpoint", "bool", "vm_writecheckpoint")

    # -- Photon --
    Photon("photon", "photoncfile", "string", "vm_photoncfile")
    Photon("photon", "photoncount", "int", "vm_photoncount")
    Photon("photon", "photongfile", "string", "vm_photongfile")
    Photon("photon", "photonminratio", "float", "vm_photonminratio")

    # -- Camera --
    Camera("camera", "curvature", "float", "vm_curvature")
    Camera("camera", "dofaspect", "float", "vm_dofaspect")
    Camera("camera", "field", "int", "vm_field")
    Camera("camera", "shuttershape", "string", "vm_shuttershape")

    # -- Object --
    Object("name", "string", "object:name")
    Object("biasnormal", "bool", "vm_biasnormal")
    Object("bumpraydisplace", "bool", "vm_bumpraydisplace")
    Object("categories", "string", "categories")
    Object("coving", "int", "vm_coving")
    Object("curvesurface", "bool", "vm_curvesurface")
    Object("curveunitst", "bool", "vm_curveunitst")
    Object("decoupleindirect", "bool", "vm_decoupleindirect")
    Object("diffuselimit", "int", "vm_pbrdiffuselimit")
    Object("diffuselimit", "int", "vm_diffuselimit")
    Object("diffusequality", "float", "vm_diffusequality")
    Object("displacebound", "float", "vm_displacebound")
    Object("displacespace", "string", "vm_displacespace")
    Object("dorayvariance", "bool", "vm_dorayvariance")
    Object("emitillum", "bool", "vm_emitillum")
    Object("filter", "string", "vm_volumefilter")
    Object("filterwidth", "float", "vm_volumefilterwidth")
    Object("flatness", "float", "vm_flatness")
    Object("flattenprocedural", "int", "vm_flattenprocedural")
    Object("flattentoroot", "int", "vm_flattentoroot")
    Object("geofilterwidth", "float", "vm_geofilterwidth")
    Object("geometrygroup", "string", "vm_geometrygroup")
    Object("gienable", "bool", "vm_gienable")
    Object("gierror", "float", "vm_gierror")
    Object("gifile", "string", "vm_gifile")
    Object("gifilemode", "string", "vm_gifilemode")
    Object("gimaxspacing", "float", "vm_gimaxspacing")
    Object("giminspacing", "float", "vm_giminspacing")
    Object("gisample", "int", "vm_gisample")
    Object("globalquality", "float", "vm_globalquality")
    Object("heightfieldtess", "int", "vm_heightfieldtess")
    Object("indirectvariance", "float", "vm_indirectvariance")
    Object("jitcurves", "bool", "vm_jitcurves")
    Object("lightcategories", "string", "lightcategories")
    Object("lightmask", "oplist", "lightmask")
    Object("lpetag", "string", "vm_lpetag")
    Object("matte", "bool", "vm_matte")
    Object("maxindirectraysamples", "int", "vm_maxindirectraysamples")
    Object("maxraysamples", "int", "vm_maxraysamples")
    Object("metavolume", "bool", "vm_metavolume")
    Object("minindirectraysamples", "int", "vm_minindirectraysamples")
    Object("minraysamples", "int", "vm_minraysamples")
    Object("motionfactor", "float", "vm_motionfactor")
    Object("osd_fvarinterp", "int", "vm_osd_fvarinterp")
    Object("osd_quality", "float", "vm_osd_quality")
    Object("osd_vtxinterp", "int", "vm_osd_vtxinterp")
    Object("overridedetail", "bool", "vm_overridedetail")
    Object("pack_mergefragments", "bool", "vm_pack_mergefragments")
    Object("pack_refineoptions", "string", "vm_pack_refineoptions")
    Object("pack_sequencesubsteps", "int", "vm_pack_sequencesubsteps")
    Object("packinstance", "bool", "vm_packinstance")
    Object("photonmodifier", "int", "vm_photonmodifier")
    Object("pointscale", "float", "vm_pointscale")
    Object("procuseroottransform", "bool", "vm_procuseroottransform")
    Object("pscalediameter", "bool", "vm_pscalediameter")
    Object("raypredice", "int", "vm_raypredice")
    Object("rayshade", "bool", "vm_rayshade")
    Object("rayweight", "float", "vm_rayweight")
    Object("redice", "bool", "vm_redice")
    Object("reflectcategories", "string", "reflectcategories")
    Object("reflectionquality", "float", "vm_reflectionquality")
    Object("reflectlimit", "int", "vm_pbrreflectlimit")
    Object("reflectlimit", "int", "vm_reflectlimit")
    Object("reflectmask", "oplist", "reflectmask")
    Object("refractcategories", "string", "refractcategories")
    Object("refractionquality", "float", "vm_refractionquality")
    Object("refractlimit", "int", "vm_pbrrefractlimit")
    Object("refractlimit", "int", "vm_refractlimit")
    Object("refractmask", "oplist", "refractmask")
    Object("renderable", "bool", "vm_renderable")
    Object("renderpoints", "int", "vm_renderpoints")
    Object("renderpointsas", "int", "vm_renderpointsas")
    Object("rendersubd", "bool", "vm_rendersubd")
    Object("rendersubdcurves", "bool", "vm_rendersubdcurves")
    Object("rendervisibility", "string", "vm_rendervisibility")
    Object("rmbackface", "bool", "vm_rmbackface")
    Object("samplecoving", "bool", "vm_samplecoving")
    Object("samplecovingexpansion", "float", "vm_samplecovingexpansion")
    Object("samplingquality", "float", "vm_samplingquality")
    Object("shadingquality", "float", "vm_shadingquality")
    Object("sharedisplace", "bool", "vm_sharedisplace")
    Object("smoothP", "bool", "vm_smoothP")
    Object("smoothcolor", "bool", "vm_smoothcolor")
    Object("ssslimit", "int", "vm_ssslimit")
    Object("sssquality", "float", "vm_sssquality")
    Object("subdgroup", "string", "vm_subdgroup")
    Object("subdstyle", "string", "vm_subdstyle")
    Object("traceblur", "bool", "vm_traceblur")
    Object("truedisplace", "bool", "vm_truedisplace")
    Object("usenforpoints", "bool", "vm_usenforpoints")
    Object("variance", "float", "vm_variance")
    Object("velocitybound", "float", "vm_velocitybound")
    Object("velocityquality", "float", "vm_velocityquality")
    Object("volumedensity", "float", "vm_volumedensity")
    Object("volumedpdzfov", "bool", "vm_volumedpdzfov")
    Object("volumeiso", "bool", "vm_volumeiso")
    Object("volumeisodefault", "bool", "vm_volumeisodefault")
    Object("volumelimit", "int", "vm_volumelimit")
    Object("volumenormal", "bool", "vm_volumenormal")
    Object("volumequality", "float", "vm_volumequality")
    Object("volumesamples", "int", "vm_volumesamples")
    Object("volumesamplingchannel", "string", "vm_volumesamplingchannel")
    Object("volumeshadowsteprate", "float", "vm_volumeshadowsteprate")
    Object("volumesteprate", "float", "vm_volumesteprate")
    Object("volumesurface", "bool", "vm_volumesurface")
    Object("volumeuniform", "bool", "vm_volumeuniform")
    Object("volumeuniformflipthresh", "float", "vm_volumeuniformflipthresh")
    Object("volumeuniformtype", "int", "vm_volumeuniformtype")
    Object("volumeupvector", "float", "vm_volumeupvector")
    Object("volumezerothresh", "float", "vm_volumezerothresh")

    # -- Light --
    Light("__nondiffuse", "bool", "vm_nondiffuse")
    Light("__nonspecular", "bool", "vm_nonspecular")
    Light("activeradius", "float", "vm_activeradius")
    Light("areafullsphere", "bool", "vm_areafullsphere")
    Light("areamap", "string", "vm_areamap")
    Light("areashape", "string", "vm_areashape")
    Light("areasize", "float", "vm_areasize")
    Light("envangle", "float", "vm_envangle")
    Light("envintensity", "float", "vm_envintensity")
    Light("importancelevels", "int", "vm_importancelevels")
    Light("lightcache", "bool", "vm_lightcache")
    Light("photontarget", "string", "vm_photontarget")
    Light("photonweight", "float", "vm_photonweight")
    Light("raybackground", "bool", "vm_raybackground")
    Light("shadowcategories", "string", "shadowcategories")
    Light("shadowmask", "oplist", "shadowmask")

    # -- Fog --
    Fog("name", "string", "object:name")
    Fog("categories", "string", "categories")
    Fog("lightcategories", "string", "lightcategories")
    Fog("lightmask", "oplist", "lightmask")

    # -- Geometry --
    Geometry("computeN", "bool", "vm_computeN")
    Geometry("segmentattrs", "string", "vm_segmentattrs")
    Geometry("timescale", "float", "vm_motiontimescale")
    Geometry("volumevelocitynames", "string", "vm_volumevelocitynames")

    # -- Deep --
    Deep("shadow", "OpenEXR.attributes", "string", "vm_image_exr_attributes")
    Deep("shadow", "compositing", "bool", "vm_dsmcompositing")
    Deep("shadow", "deepcompression", "int", "vm_dsmcompression")
    Deep("shadow", "depth_interp", "string", "vm_dsmdepthinterp")
    Deep("shadow", "depth_mode", "string", "vm_dsmdepthmode")
    Deep("shadow", "depth_planes", "string", "vm_dsmdepthplanes")
    Deep("shadow", "filename", "string", "vm_dsmfilename", ['$HIP/dsm.rat'])
    Deep("shadow", "mipmaps", "bool", "vm_dsmmipmaps")
    Deep("shadow", "ofsize", "int", "vm_dsmofsize")
    Deep("shadow", "ofstorage", "string", "vm_dsmofstorage")
    Deep("shadow", "pzstorage", "string", "vm_dsmpzstorage")
    Deep("shadow", "zbias", "float", "vm_dsmzbias")

    # -- Deep --
    Deep("camera", "OpenEXR.attributes", "string", "vm_image_exr_attributes")
    Deep("camera", "compositing", "bool", "vm_dcmcompositing")
    Deep("camera", "deepcompression", "int", "vm_dcmcompression")
    Deep("camera", "depth_interp", "string", "vm_dcmdepthinterp")
    Deep("camera", "depth_mode", "string", "vm_dcmdepthmode")
    Deep("camera", "depth_planes", "string", "vm_dcmdepthplanes")
    Deep("camera", "filename", "string", "vm_dcmfilename", ['$HIP/dcm.rat'])
    Deep("camera", "mipmaps", "bool", "vm_dcmmipmaps")
    Deep("camera", "ofsize", "int", "vm_dcmofsize")
    Deep("camera", "ofstorage", "string", "vm_dcmofstorage")
    Deep("camera", "pzstorage", "string", "vm_dcmpzstorage")
    Deep("camera", "zbias", "float", "vm_dcmzbias")

    # -- Measure --
    Measure("nonraster", "offscreenquality", "float", "vm_measureoffscreenquality", skipdefault=False)
    Measure("nonraster", "zimportance", "float", "vm_measurezimportance", skipdefault=False)

    # -- Bokeh --
    Bokeh("file", "-f", "string", "vm_bokehfile")
    Bokeh("file", "-r", "float", "vm_bokehrotation")

    # -- IPlane --
    IPlane("dither", "float", "vm_dither")
    IPlane("gain", "float", "vm_gain")
    IPlane("gamma", "float", "vm_gamma")
    IPlane("lightexport", "string", "vm_lightexport", mainimage=False)
    IPlane("pfilter", "string", "vm_pfilter")
    IPlane("quantize", "string", "vm_quantize")
    IPlane("sfilter", "string", "vm_sfilter")
    IPlane("whitepoint", "float", "vm_whitepoint")

    # -- ImageOption --
    ImageOption("Cineon.cingamma", "float", "vm_image_cineon_gamma")
    ImageOption("Cineon.cinlut", "string", "vm_image_cineon_lut")
    ImageOption("Cineon.cinspace", "string", "vm_image_cineon_space")
    ImageOption("Cineon.cinwhite", "int", "vm_image_cineon_whitepoint")
    ImageOption("IPlay.bgimage", "string", "vm_image_mplay_bgimage")
    ImageOption("IPlay.direction", "string", "vm_image_mplay_direction")
    ImageOption("IPlay.gamma", "float", "vm_image_mplay_gamma")
    ImageOption("IPlay.houdiniportnum", "int", "mplay:port")
    ImageOption("IPlay.label", "string", "vm_image_mplay_label")
    ImageOption("IPlay.lut", "string", "vm_image_mplay_lut")
    ImageOption("IPlay.sockethost", "string", "vm_image_mplay_sockethost")
    ImageOption("IPlay.socketport", "int", "vm_image_mplay_socketport")
    ImageOption("JPEG.quality", "int", "vm_image_jpeg_quality")
    ImageOption("OpenEXR.attributes", "string", "vm_image_exr_attributes")
    ImageOption("OpenEXR.compression", "string", "vm_image_exr_compression")
    ImageOption("OpenEXR.dwa_compression", "float", "vm_image_exr_dwa_level")
    ImageOption("OpenEXR.enablepostprocess", "bool", "vm_image_exr_postprocess")
    ImageOption("OpenEXR.storage", "string", "vm_image_exr_storage")
    ImageOption("OpenEXR.tilex", "int", "vm_image_exr_tilex")
    ImageOption("OpenEXR.tiley", "int", "vm_image_exr_tiley")
    ImageOption("PNG.frompremult", "string", "vm_image_png_frompremult")
    ImageOption("RAT.color", "string", "vm_image_rat_color")
    ImageOption("RAT.compression", "string", "vm_image_rat_compression")
    ImageOption("RAT.makemips", "bool", "vm_image_rat_makemips")
    ImageOption("TIFF.compression", "string", "vm_image_tiff_compression")
    ImageOption("TIFF.predictor", "string", "vm_image_tiff_predictor")
    ImageOption("artist", "string", "vm_image_artist")
    ImageOption("comment", "string", "vm_image_comment")
    ImageOption("hostname", "string", "vm_image_hostname")

