#ifndef _VBUFFERSW_COMMON_SLANGH
#define _VBUFFERSW_COMMON_SLANGH

#define CULL_NONE 0
#define CULL_BACK 1
#define CULL_FRONT 2

#ifndef CULL_MODE
#define CULL_MODE CULL_BACK
#endif

#ifndef USE_PP_JITTER
#define USE_PP_JITTER true
#endif

#ifndef USE_D64
#define USE_D64 true
#endif

#ifndef COMPUTE_DEPTH_OF_FIELD
#define COMPUTE_DEPTH_OF_FIELD false
#endif

#ifndef COMPUTE_MOTION_BLUR
#define COMPUTE_MOTION_BLUR false
#endif

#endif  // _VBUFFERSW_COMMON_SLANGH