//#include "Scene/SceneDefines.slangh"
//#include "Utils/Math/MathConstants.slangh"

//import Scene.Camera.CameraData;

//import Utils.Sampling.SampleGenerator;
//import Utils.Sampling.VisibilitySamplesContainer;
//import Utils.Noise.STBNGenerator;
//import Utils.Math.MathHelpers;
//import Utils.Math.PackedFormats;
//import Utils.Math.FormatConversion;
//import Utils.Shading.VisbufferUtils;


[numthreads(16, 16, 1)]
void main(uint3 groupID : SV_GroupID, uint groupIdx : SV_GroupIndex) {
    
}